[package]
name = "clavis"
version = "0.1.0"
edition = "2021"
description = "A Rust library for secure, encrypted communication over asynchronous streams"
authors = ["Pyro"]
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/pyrohost/clavis"
keywords = ["encryption", "communication", "async", "security"]
categories = ["cryptography", "asynchronous", "network-programming"]

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
aes-gcm = "0.10.3"
rand = "0.8"
thiserror = "1.0"
aes-gcm-siv = "0.11.1"
sha2 = "0.10.8"
hkdf = "0.12.4"
bincode = "1.3.3"
tracing = "0.1.40"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["async_tokio"] }

[badges]
maintenance = { status = "actively-developed" }
