[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
clavis = { path = "../../crates/clavis" }
packets = { version = "0.1.0", path = "../packets" }
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
